### ISSUE TITLE
[Question/Help?] cant compile anymore :(

### ISSUE THREAD

**Issue by guidol70** [MockbaTheBorg/RunCPM#131]
The last time I did compile successful at the 31.08.2021 on my TTGO VGA32
and now I I get every time the same errors while compiling :(

I tested older RunCPM-versions (which did compile in th past), different sdfat (2.04.-2.1.0)
and ESP32 Arduino Support 1.0.6 and 2.0.0 and older and newer FabGL-version, but I do get the follwing error - do you got a hint? Seems to be on another end where it fails?
(or should I completly resinstall the Arduino-IDE / HW-Support and Librarys?)

```
Arduino: 1.8.15 (Windows 10), Board: "ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, None"

In file included from Q:\1A_RunCPM\RunCPM_v5_5_master_TTGO_VGA32\RunCPM-master\RunCPM_VGA32_v5_5_Patch\RunCPM_VGA32_v5_5_Patch.ino:61:0:

Q:\1A_RunCPM\RunCPM_v5_5_master_TTGO_VGA32\RunCPM-master\RunCPM_VGA32_v5_5_Patch\abstraction_arduino.h: In function 'bool _RamLoad(char*, uint16)':

abstraction_arduino.h:24:2: error: 'File' was not declared in this scope

  File f;

  exit status 1

'File' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

```

**Comment by guidol70** [comment]
Now Iam at Arduino-IDE v1.8.6, SDFat v2.1.0, ESP HW Support v1.0.6
and
FabGL-github-master from the 02.08.2021

And now RunCPM v5.6 does compile - but a newer FabGL-master does give me errors... 
I will ask there :)

**Comment by MockbaTheBorg** [comment]
Hi @guidol70 I see you are able to build correctly now?
Should we close this one?

**Comment by guidol70** [comment]
> Hi @guidol70 I see you are able to build correctly now?
> Should we close this one?

We could close this ;)
Iam using the "old" /src/fabutils.cpp from FabGL 1.0.4 and the "old" ESP32-Core v1.0.6
